/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hcss.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.hcss.bean.LoginTO;
import com.hcss.delegate.SecurityUserDelegate;
import com.hcss.exception.ConnectionException;
import com.hcss.utill.UtilConstants;


/**
 * MyEclipse Struts Creation date: 08-31-2012
 * 
 * XDoclet definition:
 * 
 * @struts.action scope="request" validate="true"
 * @struts.action-forward name="failure" path="/NewUserRegistration.jsp"
 * @struts.action-forward name="success" path="/NewUserRegistration.jsp"
 */
public class CheckUserAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String username = request.getParameter("loginid");
		try {
			// String a="Available";
			String user = new SecurityUserDelegate().checkUser(username);
					if (user.equals("")) {
				request.setAttribute("status", UtilConstants._USER_AVAILABLE);
				return mapping.findForward("failure");
			} else
				request
						.setAttribute("status",
								UtilConstants._USER_NO_AVAILABLE);
			return mapping.findForward("failure");
		} catch (Exception e) {
			request.setAttribute("status", UtilConstants._USER_AVAILABLE);
			return mapping.findForward("failure");
		}
	}
}