/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hcss.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.hcss.bean.LoginTO;
import com.hcss.cryptutil.Encryption;
import com.hcss.delegate.SecurityUserDelegate;
import com.hcss.exception.ConnectionException;
import com.hcss.exception.LoginException;
import com.hcss.utill.UtilConstants;

/**
 * MyEclipse Struts Creation date: 08-29-2012
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * @struts.action-forward name="failure"
 *                        path="/Status.jsp?status=Invalid Username and Password"
 * @struts.action-forward name="success" path="/AdminHome.jsp"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		System.out.println("Entered in action file");
		// TODO Auto-generated method stub
		HttpSession session = request.getSession();
		Encryption ec = new Encryption();
		int a[] = ec.ecies_ex(request.getParameter("password"));
		String abc = "";
		for (int i = 0; i < a.length; i++) {
			abc = abc + a[i] + ",";
		}
		//System.out.println("new password after change"+abc+"ENDS HERE ");
		LoginTO loginTO = (LoginTO) form;
		loginTO.setPassword(abc);
		LoginTO login = null;
		try {
			System.out.println("Entered in try");
			login = new SecurityUserDelegate().loginCheck(loginTO);
			System.out.println("got login type");
			System.out.println(login.getLogintype());
			request.setAttribute("status", "Welcome " + login.getLoginid());
			session.setAttribute(UtilConstants._LOGINID, login.getLoginid());
			session.setAttribute(UtilConstants._USERID, login.getUseridref());
			session.setAttribute(UtilConstants._ROLE, login.getLogintype());
			if (login.getLogintype().equalsIgnoreCase(UtilConstants._ADMIN)) {
				return mapping.findForward("admin");
			} else if (login.getLogintype().equalsIgnoreCase(
					UtilConstants._USER)) {
				return mapping.findForward("user");
			} else {
				request.setAttribute("status", UtilConstants._INVALID_USER);
				return mapping.findForward("failure");
			}
		} catch (ConnectionException e) {
			System.out.println("Entered in catch connection exception");
			System.out.println(e.getMessage());
			request.setAttribute("status", e.getMessage());
			return mapping.findForward("failure");
		} catch (LoginException e) {
			System.out.println("Entered in catch login exception");
			request.setAttribute("status", e.getMessage());
			return mapping.findForward("failure");
		}
	}
}