/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hcss.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 08-30-2012
 * 
 * XDoclet definition:
 * 
 * @struts.action scope="request" validate="true"
 * @struts.action-forward name="logout"
 *                        path="/LoginForm.jsp?status=Logout Successfully "
 */
public class LogoutAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		// TODO Auto-generated method stub
		HttpSession session = request.getSession();
		session.setAttribute("userid", null);
		session.setAttribute("role", null);
		session.setAttribute("loginid", null);
		request.setAttribute("status", "logged out successfully.....");
		session.invalidate();
		return mapping.findForward("logout");
	}
}