/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hcss.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.hcss.bean.PassportTO;
import com.hcss.delegate.SecurityUserDelegate;
import com.hcss.delegate.UserPersonalDelegate;
import com.hcss.utill.UtilConstants;

/** 
 * MyEclipse Struts
 * Creation date: 09-07-2012
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="failure" path="/Status.jsp"
 * @struts.action-forward name="success" path="/Status.jsp"
 */
public class UpdateUserStatusAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		boolean flag = false;
		
		try {
			flag = new SecurityUserDelegate().updateUserStatus(Integer.parseInt(request.getParameter("userid")));
			if (flag) {
				request.setAttribute("status",
						UtilConstants._UPDATE_USER_STATUS);
				return mapping.findForward("success");
			} else {
				request.setAttribute("status",
						UtilConstants._UPDATE_USER_STATUS_FAIL);
				return mapping.findForward("failure");
			}
		} catch (Exception e) {
			System.out.println(e);
			request.setAttribute("status", e.getMessage());
			return mapping.findForward("failure");
		}
	
	}
}