/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hcss.action;

import java.util.Vector;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.hcss.bean.UserProfileFormBean;
import com.hcss.delegate.SecurityUserDelegate;
import com.hcss.utill.UtilConstants;

/** 
 * MyEclipse Struts
 * Creation date: 09-06-2012
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="failure" path="/Status.jsp"
 * @struts.action-forward name="success" path="/ViewListUsers.jsp"
 */
public class ViewRegisteredUsersAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String path = "";
		String user = request.getParameter("user");
		Vector<UserProfileFormBean> userProfileFormBean = null;
		try {
			path = request.getRealPath("/images");
			userProfileFormBean = new SecurityUserDelegate().viewUserList(user, path);
			if (userProfileFormBean != null) {
				request
						.setAttribute("status",
								UtilConstants._USERS_LIST_INFO);
				request.setAttribute("userinfo", userProfileFormBean);
				return mapping.findForward("success");

			} else {
				request.setAttribute("status", UtilConstants._NO_USER_PROFILE);
				return mapping.findForward("failure");
			}
		} catch (Exception e) {
			request.setAttribute("status", e.getMessage());
			return mapping.findForward("failure");
		}
	}
}