/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hcss.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.hcss.bean.PancardTO;
import com.hcss.bean.UserImpFilesTO;
import com.hcss.delegate.UserPersonalDelegate;
import com.hcss.utill.UtilConstants;

/** 
 * MyEclipse Struts
 * Creation date: 09-05-2012
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="failure" path="/Status.jsp"
 * @struts.action-forward name="success" path="/UpdatePanDetails.jsp"
 */
public class ViewUpdatePanDetailsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		int panid = Integer.parseInt(request.getParameter("panid"));
		PancardTO pancardTO = null;
		try {
			System.out.println("hsiiiiiiii");
			pancardTO = new UserPersonalDelegate().viewUpdatePanDetails(panid);
			if (pancardTO != null) {
				request.setAttribute("PancardTO", pancardTO);
				request.setAttribute("status",
						UtilConstants._VIEW_PANCARD_DETAILS);
				return mapping.findForward("success");
			} else {
				request.setAttribute("status",
						UtilConstants._VIEW_PANCARD_DETAILS_FAIL);
				return mapping.findForward("failure");
			}
		} catch (Exception ce) {
			request.setAttribute("status", ce.getMessage());
			return mapping.findForward("failure");
		}
	}
}